### ISSUE TITLE
[Feature]: Hope it can support listening to system screenshots

### ISSUE THREAD

**Issue by acmenlei** [iamthenoah/clipeasy#1]
Thank you very much for sharing, I found that it cannot listen to screenshots. If it could support that, it would be perfect!

**Comment by iamthenoah** [comment]
Hello there,

This library was designed with the sole purpose of interacting with a system's clipboard. Having a feature that captures screenshot events falls outside of scope of this project and I don't believe that it would add any value with respect to managing a clipboard.

I appreciate your feedback however and encourage you to explore how this may be implelmented with clipeasy ;).
