### ISSUE TITLE
Are you aware of `clipboard-event-ipaste`?

### ISSUE THREAD

**Issue by felipecrs** [iamthenoah/clipeasy#2]
Hi, I was searching for a library that could replace https://github.com/kenan2002/electron-clipboard-ex and I found yours, which seems awesome.

However, when searching on NPM, I found the following:

https://www.npmjs.com/package/clipboard-event-ipaste

Which apart from the name, seems to be a fork of yours with newer code (considering the publish date and version).

Since such fork cannot be found in GitHub, I was wondering if you knew anything about it.

**Comment by iamthenoah** [comment]
Hi, 

I wasn't aware, thank you for taking the time to bring this to my attention. I'll look into it in more details. 

I'm glad you find this library helpful. The goal of this project was in fact to replace clipboard-ex ;). 

Linux support is still a WIP and I don't have an eta for an update unfortunately. 

Ps. I've been busy lately and your comment went completely over my head.
